### ISSUE TITLE
Unable to start the application from first run (ReflectionTypeLoadException)

### ISSUE THREAD

**Issue by deadalusai** [brickpile/brickpile#171]
I'm unable to start the application from Visual Studio. Steps to recreate (using VS2013 Update 4):

1. Create an Empty ASP.NET application with MVC and Web API
2. `Install-Package BrickPile -Pre -DependencyVersion Highest`
3. Start the app in IIS Express

The application crashes with a `ReflectionTypeLoadException` on [this line][brick-pile-initializer] in the `Initializer` class. The missing assembly is `ICSharpCode.NRefactory.CSharp` (and possibly others).

[brick-pile-initializer]: https://github.com/brickpile/brickpile/blob/f95849332e27e0306d30ee7ed4b9403989122a8f/BrickPile.UI/App_Start/Initializer.cs#L90

**Comment by marcuslindblom** [comment]
@deadalusai added the proposed extension method to the [latest release](https://www.nuget.org/packages/BrickPile/0.5.3), see this [commit](https://github.com/brickpile/brickpile/commit/eb1bbc124e37480737bb85f08c13b943c5fc89f7)
