### ISSUE TITLE
No page types?

### ISSUE THREAD

**Issue by yooakim** [brickpile/brickpile#173]
I just did a clean install into a new project. When I run the project for the first time I am asked to supply website name, username etc. The next thing that happens is that i need to select a page type. The problem is that there are no page types available? 

What am I doing wrong?

![nopagetype](https://cloud.githubusercontent.com/assets/862546/5701337/126d4ffc-9a4a-11e4-8a8d-85ce43965bbe.PNG)

Cheers,
Joakim

**Comment by marcuslindblom** [comment]
@yooakim When you install brickpile you don't get any page types. It's up to you to create the page types you need. Download this [example package](http://cl.ly/ZGIH) and use them, or just look at them to see how you can create your own.

**Comment by yooakim** [comment]
Ok, thanks! I'll explore & learn!
