### ISSUE TITLE
OwinStartup attribute Conflict

### ISSUE THREAD

**Issue by 19nine78** [brickpile/brickpile#174]
Hi,

I'm getting the following when hitting F5 after a fresh install into an new MVC5 project.

Not really sure where to start debugging this myself, any pointers welcomed.

![capture](https://cloud.githubusercontent.com/assets/1195002/5789917/7de2cdc6-9e77-11e4-9b85-59266dabf7ac.PNG)

**Comment by marcuslindblom** [comment]
@19nine78 Did you create a test project for your solution? It seems like there are an assembly in the `bin` directory interfering with brickpile?

**Comment by 19nine78** [comment]
I tried again without creating a unit test project and initially got a similar error. The solution was to comment out the [assembly: OwinStartupAttribute(typeof(WebApplication2.Startup))] thats in the Startup.cs thats created by the default mvc project.

After doing that it all seems to work.
